title: Hiddify
background: "background.png"
window:
  size:
    width: 512
    height: 512
contents:
  - x: 448
    y: 344
    type: link
    path: "/Applications"
  - x: 192
    y: 344
    type: file
    path: Hiddify.app
